apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-headers-middleware
  namespace: asset-v3
spec:
  headers:
    customResponseHeaders:
      X-Frame-Options: "DENY"
      Content-Security-Policy: "frame-ancestors 'none'"
      X-Content-Type-Options: "nosniff"
      X-XSS-Protection: "1; mode=block"
      Referrer-Policy: "strict-origin-when-cross-origin"

